### ISSUE TITLE
500 service error when creating a meme

### ISSUE THREAD

**Issue by zedtux** [nicolewhite/slack-meme#41] opened 2018-06-19 13:57 UTC
I'm trying this little thing, using the Dockerfile, and I have all set and running.

When I send `/meme help` in slack, I got a reply, when I send `/meme templates` I see the list of templates, but when I'm using the command from the `README.md` : `/meme success;we have;a meme bot` I have an error :

```
Darn - that slash command didn't work (error message: `500_service_error`). Manage the command at Slack Meme.
```

And from docker-compose :

```
slack-meme_1   | 172.YY.Y.2 - - [19/Jun/2018 13:53:18] "POST / HTTP/1.1" 500 -
nginx          | sm.domain.com XX.XXX.XX.XX - - [19/Jun/2018:13:53:18 +0000] "POST / HTTP/1.1" 500 291 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
```

And I don't know where I can see the full error.

I did a `tail -f /var/log/**/* /var/log/*` within the slack-meme container, but got nothing here.

Where can I see the full error? Is there a place in this app where a log file lives?

**Comment by phyzalis** [comment] 2018-06-20 12:47
+1 Same here

**Comment by zedtux** [comment] 2018-06-20 12:59
I updated the Docker image [as described in one of your comment from an older issue](https://github.com/nicolewhite/slack-meme/issues/4#issuecomment-134063785) @nicolewhite, adding the `debug=True` in the `run.py` file, and here is the output:

```
slack-meme_1   | /usr/local/lib/python2.7/dist-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ANSI_X3.4-1968'
slack-meme_1   |   BrokenFilesystemWarning)
slack-meme_1   | 172.YY.Y.2 - - [20/Jun/2018 12:56:45] "POST / HTTP/1.1" 500 -
slack-meme_1   | Traceback (most recent call last):
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
nginx          | sm.domain.com XX.XX.XXX.XXX - - [20/Jun/2018:12:56:45 +0000] "POST / HTTP/1.1" 500 18859 "-" "Slackbot 1.0 (+https://api.slack.com/robots)"
slack-meme_1   |     return self.wsgi_app(environ, start_response)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
slack-meme_1   |     response = self.make_response(self.handle_exception(e))
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
slack-meme_1   |     reraise(exc_type, exc_value, tb)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
slack-meme_1   |     response = self.full_dispatch_request()
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
slack-meme_1   |     rv = self.handle_user_exception(e)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
slack-meme_1   |     reraise(exc_type, exc_value, tb)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
slack-meme_1   |     rv = self.dispatch_request()
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
slack-meme_1   |     return self.view_functions[rule.endpoint](**req.view_args)
slack-meme_1   |   File "/app/slack/views.py", line 33, in meme
slack-meme_1   |     user = slack.find_user_info(user_id)
slack-meme_1   |   File "/app/slack/models.py", line 94, in find_user_info
slack-meme_1   |     user = response.json()["user"]
slack-meme_1   | KeyError: 'user'
```

**Comment by zedtux** [comment] 2018-07-18 05:15
@nicolewhite any chance to get an input from you? We are hungry of meme here 😆

**Comment by aoberoi** [comment] 2018-07-18 09:07
Hey folks, I was also able to reproduce this issue. I did it without using Docker, so that's not the issue. I'll see if there's a quick solution I can come up with.

**Comment by aoberoi** [comment] 2018-07-18 22:26
I was able log out the response from the API request to Slack:

```
users.info response: {u'needed': u'users:read', u'provided': u'identify,commands,incoming-webhook', u'ok': False, u'error': u'missing_scope'}
```

It turns out the API token supplied did not have the right scope: `users:read`. Once I added it and reinstalled the app into the workspace, it started working again 🎉.

We should update the docs to reflect this, so I'm opening a new issue for that.

**Comment by aoberoi** [comment] 2018-07-18 22:35
The change has been merged. Please give it a shot and confirm that it now works, and then I'll close this issue.

**Comment by PaulBrandt** [comment] 2018-07-19 12:36
For us it does work now when using image-urls. To use templates we had to switch to python 2.
Sadly the bot does not use the users name and image. Also it allways posts into one channel no matter where you executed the command.

**Comment by aoberoi** [comment] 2018-07-19 13:44
@PaulBrandt great to hear! sounds like i can close this issue then.

#42 sounds like the right place for the custom image issues. (python 3)

#34 would enable the bot to post into whichever channel the command was triggered in

i think its reasonable to want the bot to use the image and name of the user who triggered it, but i haven't heard that request before. would you mind making a new issues for that idea?

**Closed as completed by aoberoi** 2018-07-19 13:44 UTC

**Comment by PaulBrandt** [comment] 2018-07-19 14:14
Yes this issue is resolved. I agree on #42 as I stated in comments there.
Both our problems (Not using the users avatar + name) and posting in the wrong channel was fixed by not using the webhook the app created, but one that we created on our own.
All working fine for us now :tada:

**Comment by aoberoi** [comment] 2018-07-19 14:50
@PaulBrandt oh that's not what i'd expect, there should be no difference between the avatar and name based on whether the webhook is part of the app or from a custom integration (which is what i assume you mean when you created it on your own). in both cases, the name / avatar would be the one you assign to the app / integration, not the user who triggered it. for the app, you would make those assignments on the app configuration page (upload an image and change the name), while with a custom integration webhook you would do it on the setup page as well. did you find that your own webhook uses the name / avatar of the user who triggered the slash command?

**Comment by zedtux** [comment] 2018-07-19 15:13
Thank you @aoberoi for your update. I followed what you recommended, and it isn't working for me, but the error changed :

```
slack-meme_1   | 172.18.0.3 - - [19/Jul/2018 15:12:37] "POST / HTTP/1.1" 500 -
slack-meme_1   | Traceback (most recent call last):
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
slack-meme_1   |     return self.wsgi_app(environ, start_response)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
slack-meme_1   |     response = self.make_response(self.handle_exception(e))
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
slack-meme_1   |     reraise(exc_type, exc_value, tb)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
slack-meme_1   |     response = self.full_dispatch_request()
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
slack-meme_1   |     rv = self.handle_user_exception(e)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
slack-meme_1   |     reraise(exc_type, exc_value, tb)
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
slack-meme_1   |     rv = self.dispatch_request()
slack-meme_1   |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
slack-meme_1   |     return self.view_functions[rule.endpoint](**req.view_args)
slack-meme_1   |   File "/app/slack/views.py", line 33, in meme
slack-meme_1   |     user = slack.find_user_info(user_id)
slack-meme_1   |   File "/app/slack/models.py", line 95, in find_user_info
slack-meme_1   |     file.write(response.json())
slack-meme_1   | TypeError: expected a string or other character buffer object
```

Do you have any idea about this?

**Comment by aoberoi** [comment] 2018-07-19 15:17
@zedtux it looks like you might have modified the code in `models.py`, since that's not what line 95 has on the latest code here. could you try resetting that file back and seeing if you still have the issue?

**Comment by zedtux** [comment] 2018-07-19 15:18
Oh yes, sure. I'll do it. Thank you.

**Comment by zedtux** [comment] 2018-07-19 15:35
Oh yeah, reverting the code is working ! 👍 Thank you so much @aoberoi :)

**Comment by aoberoi** [comment] 2018-07-19 18:34
@PaulBrandt actually, i understand what's happening now. this is a product feature for Apps in work.

impersonation (setting the `username` and `icon_url` values) has been relegated as one of the "bad parts" of the incoming webhooks as custom integrations. so that usage has been restricted in the newer app-contained incoming webhooks.

if you think about it, this should make sense. you don't want to give external services the power to masquerade as anyone. the first time someone does something nefarious with this, its bound to make people ask for the service to be removed. while its totally up to you, i encourage you to stick with the app-based incoming webhook as described.

meanwhile, the folks here at Slack are considering how we can apps sending messages on behalf of a certain user in a clear and understood way.
